### ISSUE TITLE
Unable to send results to reportportal.io

### ISSUE THREAD

**Issue by nkrishna79** [NHP95/ReportPortal-Katalon-Integration#2]
Hi 
I followed your tutorial and when I run the testsuite, I get the below error. Any thoughts? 
2019-04-01 16:09:45.915 ERROR c.k.katalon.core.main.TestSuiteExecutor  - ❌ Unable to send request (Root cause: java.net.MalformedURLException: no protocol: null/null/launch
	at com.kms.katalon.core.webservice.common.RestfulClient.sendRequest(RestfulClient.java:63)
	at com.kms.katalon.core.webservice.common.RestfulClient.send(RestfulClient.java:49)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword$_sendRequest_closure1.doCall(SendRequestKeyword.groovy:53)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword$_sendRequest_closure1.call(SendRequestKeyword.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:66)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword.sendRequest(SendRequestKeyword.groovy:48)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword.execute(SendRequestKeyword.groovy:43)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:56)
	at com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords.sendRequest(WSBuiltInKeywords.groovy:40)
	at com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords$sendRequest.call(Unknown Source)
	at com.extension.reportportal.service.LaunchService.startLaunch(LaunchService.groovy:34)
	at com.extension.reportportal.service.LaunchService$startLaunch.call(Unknown Source)
	at com.extension.reportportal.listener.ReportPortalListener.<init>(ReportPortalListener.groovy:34)
	at IDVTestSuite.setUp(IDVTestSuite.groovy:37)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:175)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:154)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:153)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:157)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1554131373669.run(TempTestSuite1554131373669.groovy:35)

**Comment by NHP95** [comment]
Can I see your endpoint value (RP_HOST) in your execution profile ?

**Comment by nkrishna79** [comment]
This is my RP_HOST name: endpoint: http://dt-docker-02:8080/api/v1

**Comment by NHP95** [comment]
> This is my RP_HOST name: endpoint: http://dt-docker-02:8080/api/v1

It is a valid one. However, the error message indicates that something went wrong with the RP_HOST and the RP_NAME. I've just checked it and mine still works fine. 

Below is my execution profile.

![image](https://user-images.githubusercontent.com/29943323/57012193-801a9800-6c2f-11e9-933a-1dec1c8e46ef.png)

**Comment by nkrishna79** [comment]
I have added this to my test suite. Is this the right way?
![image](https://user-images.githubusercontent.com/37705580/57078275-de09b700-6ce5-11e9-8f7f-67e8350b1d94.png)

**Comment by NHP95** [comment]
> I have added this to my test suite. Is this the right way?
> ![image](https://user-images.githubusercontent.com/37705580/57078275-de09b700-6ce5-11e9-8f7f-67e8350b1d94.png)

Yes, it is. Have you imported the required classes into the suite ?

**Comment by nkrishna79** [comment]
Not really. All I did was just followed your instructions. To copy the com folder and then to run build.gradle file. Can you tell what all classes should I import into this suite?

**Comment by NHP95** [comment]
Here is what your suite should look like.

![image](https://user-images.githubusercontent.com/29943323/57079131-eb409900-6d19-11e9-8b3e-89e857511510.png)

**Comment by nkrishna79** [comment]
Ok looks like we are getting there... but have this issue now 
2019-05-02 14:40:59.951 ERROR c.k.katalon.core.main.TestSuiteExecutor  - ❌ Unable to send request (Root cause: java.net.MalformedURLException: no protocol: null/null/launch
	at com.kms.katalon.core.webservice.common.RestfulClient.sendRequest(RestfulClient.java:65)
	at com.kms.katalon.core.webservice.common.RestfulClient.send(RestfulClient.java:51)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword$_sendRequest_closure1.doCall(SendRequestKeyword.groovy:55)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword$_sendRequest_closure1.call(SendRequestKeyword.groovy)
	at com.kms.katalon.core.keyword.internal.KeywordMain.runKeyword(KeywordMain.groovy:66)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword.sendRequest(SendRequestKeyword.groovy:50)
	at com.kms.katalon.core.webservice.keyword.builtin.SendRequestKeyword.execute(SendRequestKeyword.groovy:45)
	at com.kms.katalon.core.keyword.internal.KeywordExecutor.executeKeywordForPlatform(KeywordExecutor.groovy:56)
	at com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords.sendRequest(WSBuiltInKeywords.groovy:40)
	at com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords$sendRequest.call(Unknown Source)
	at com.extension.reportportal.service.LaunchService.startLaunch(LaunchService.groovy:34)
	at com.extension.reportportal.service.LaunchService$startLaunch.call(Unknown Source)
	at com.extension.reportportal.listener.ReportPortalListener.<init>(ReportPortalListener.groovy:34)
	at IDVTestSuite.setUp(IDVTestSuite.groovy:41)
	at com.kms.katalon.core.main.ScriptEngine.runScriptMethodAsRawText(ScriptEngine.java:133)
	at com.kms.katalon.core.main.TestSuiteExecutor.runMethod(TestSuiteExecutor.java:175)
	at com.kms.katalon.core.main.TestSuiteExecutor.lambda$0(TestSuiteExecutor.java:154)
	at com.kms.katalon.core.main.TestSuiteExecutor.invokeTestSuiteMethod(TestSuiteExecutor.java:153)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:106)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:81)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:157)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1556804445085.run(TempTestSuite1556804445085.groovy:35)

**Comment by NHP95** [comment]
Can you screenshot your whole execution profile?

**Comment by nkrishna79** [comment]
![image](https://user-images.githubusercontent.com/37705580/57080064-ad2b8100-6ce9-11e9-9c2a-f56411d78e27.png)

**Comment by NHP95** [comment]
Did you execute your suite using that profile? Because what's saying in the message is that the RP_HOST is null.

**Comment by nkrishna79** [comment]
But how do I call the profile in my suite?

**Comment by NHP95** [comment]
Like this.

![image](https://user-images.githubusercontent.com/29943323/57080619-111b6d00-6d1d-11e9-87d0-612b0b243a25.png)

**Comment by nkrishna79** [comment]
okay got it trying it now. Will let you know in a minute

**Comment by nkrishna79** [comment]
I can see the launch now. Thanks for helping me through this.

**Comment by NHP95** [comment]
> I can see the launch now. Thanks for helping me through this.

Glad to hear that. I'm closing this ticket.
