### ISSUE TITLE
ArrayIndexOutOfBoundsException on executing the testsuite

### ISSUE THREAD

**Issue by jagmitsingh** [NHP95/ReportPortal-Katalon-Integration#30]
Got the katalon API Automation project integrated with ReportPortal.  And have a testsuite which contains about 30 testcases. The test suite executions fails in the middle with the following error message. Wondering if you can provide a fix for this issue.

om.extension.reportportal.service.TestItemService Can't create object on Reportportal :
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title>
Caught: java.lang.ArrayIndexOutOfBoundsException: Negative array index [-1] too large for array size 0
java.lang.ArrayIndexOutOfBoundsException: Negative array index [-1] too large for array size 0
	at com.extension.reportportal.state.StepState.getItem(StepState.groovy:17)
	at com.extension.reportportal.state.StepState$getItem$0.call(Unknown Source)
	at com.extension.reportportal.context.ReportPortalContext.getItem(ReportPortalContext.groovy:55)
	at com.extension.reportportal.context.ReportPortalContext$getItem$2.call(Unknown Source)
	at com.extension.reportportal.listener.ReportPortalListener.afterTestHandler(ReportPortalListener.groovy:80)
	at com.extension.reportportal.listener.ReportPortalListener$afterTestHandler$1.callCurrent(Unknown Source)
	at com.extension.service.base.BaseListener.handleExecutionEvent(BaseListener.groovy:16)
	at com.extension.service.base.BaseListener$handleExecutionEvent.callCurrent(Unknown Source)
	at com.extension.reportportal.listener.ReportPortalListener.handleListenerEvent(ReportPortalListener.groovy:45)
	at com.kms.katalon.core.context.internal.ExecutionEventManager.publicEvent(ExecutionEventManager.java:36)
	at com.kms.katalon.core.main.TestCaseExecutor.execute(TestCaseExecutor.java:249)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestCaseMainPhase(TestSuiteExecutor.java:169)
	at com.kms.katalon.core.main.TestSuiteExecutor.accessTestSuiteMainPhase(TestSuiteExecutor.java:142)
	at com.kms.katalon.core.main.TestSuiteExecutor.execute(TestSuiteExecutor.java:91)
	at com.kms.katalon.core.main.TestCaseMain.startTestSuite(TestCaseMain.java:157)
	at com.kms.katalon.core.main.TestCaseMain$startTestSuite$0.call(Unknown Source)
	at TempTestSuite1588276166708.run(TempTestSuite1588276166708.groovy:36)

**Comment by NHP95** [comment]
Hi @jagmitsingh,

Thanks for the info.

I've already implemented a fix in this pull request. Could u help me confirm if this works with your projects?

**Comment by jagmitsingh** [comment]
Hello @NHP95 

Thanks issue is fixed in the latest pull request. Have tested it for my project.
